name: Format 
on:
  pull_request:
      types: [opened, reopened, ready_for_review, review_requested] 
  workflow_run:
      workflows: ["Check"]
      branches: [main]
      types: 
        - completed
jobs:
  format:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        platform: [ubuntu-20.04]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: "Environment Setup"
      uses: ./.github/base
    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
    - name: Cache cargo index
      uses: actions/cache@v4
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
    - name: fmt
      run: cargo fmt --check
      shell: bash
